name: TriggerBuild
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Trigger Jenkins Pipeline with Crumb
      env:
        JENKINS_URL: https://c984-103-163-190-41.ngrok-free.app/job/Test/buildWithParameters
        JENKINS_CRUMB_URL: https://c984-103-163-190-41.ngrok-free.app/crumbIssuer/api/json
        JENKINS_USER: admin
        JENKINS_TOKEN: 114a67a3c34f96ae70a3c925303e402a80
      run: |
        # Fetch the Jenkins Crumb dynamically
        CRUMB=$(curl -s -u "$JENKINS_USER:$JENKINS_TOKEN" "$JENKINS_CRUMB_URL" | jq -r '.crumb')
        
        echo $CRUMB
        
        if [ -z "$CRUMB" ]; then
          echo "Failed to fetch Jenkins crumb. Exiting."
          exit 1
        fi
        
        # Trigger the Jenkins pipeline
        curl -X POST "https://c984-103-163-190-41.ngrok-free.app/job/Test/build" --user "admin:$JENKINS_TOKEN" -H "Jenkins-Crumb:$CRUMB"

    - name: Wait for 20 seconds before running next task
      run: sleep 20
          
    - name: Get Running Build Details
      env:
        JENKINS_URL: https://c984-103-163-190-41.ngrok-free.app/job/Test
        JENKINS_USER: admin
        JENKINS_TOKEN: 114a67a3c34f96ae70a3c925303e402a80
      run: |
        # Fetch the latest build information
        BUILD_INFO=$(curl -s -u "admin:$JENKINS_TOKEN" "https://c984-103-163-190-41.ngrok-free.app/job/Test/api/json")
        LAST_BUILD_NUMBER=$(echo "$BUILD_INFO" | jq -r '.lastBuild.number')
        echo "Monitoring build number: $LAST_BUILD_NUMBER"

        # Initialize build status
        BUILD_STATUS="null"

        # Loop until the build status is no longer "null"
        while [ "$BUILD_STATUS" == "null" ]; do
          # Fetch the latest build details
          BUILD_DETAILS=$(curl -s -u "admin:$JENKINS_TOKEN" "$JENKINS_URL/$LAST_BUILD_NUMBER/api/json")
          BUILD_STATUS=$(echo "$BUILD_DETAILS" | jq -r '.result')

          if [ "$BUILD_STATUS" == "null" ]; then
          echo "Build is still running..."
          sleep 10  # Wait for 10 seconds before checking again
          fi
        done

         # Print final build status
        echo "Build completed. Final status: $BUILD_STATUS"
      
        # # get completed build details using jq
        BUILD_NUMBER=$(echo "$BUILD_DETAILS" | jq -r '.number')
        BUILD_URL=$(echo "$BUILD_DETAILS" | jq -r '.url')
        
        echo "Build Number: $BUILD_NUMBER"
        echo "Build URL: $BUILD_URL"


        # if [ "$BUILD_STATUS" == "null" ]; then
        #   echo "Build is currently running..."
        # else
        #   echo "Build status: $BUILD_STATUS"
        # fi
