name: TriggerBuild
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Trigger Jenkins Pipeline with Crumb
      env:
        JENKINS_URL: https://d8ff-103-167-176-239.ngrok-free.app/job/Test/buildWithParameters
        JENKINS_CRUMB_URL: https://d8ff-103-167-176-239.ngrok-free.app/crumbIssuer/api/json
        JENKINS_USER: admin
        JENKINS_TOKEN: 114a67a3c34f96ae70a3c925303e402a80
      run: |
        # Fetch the Jenkins Crumb dynamically
        CRUMB=$(curl -s -u "$JENKINS_USER:$JENKINS_TOKEN" "$JENKINS_CRUMB_URL" | jq -r '.crumb')
        
        echo $CRUMB
        
        if [ -z "$CRUMB" ]; then
          echo "Failed to fetch Jenkins crumb. Exiting."
          exit 1
        fi
        
        # Trigger the Jenkins pipeline
        curl -X POST "https://d8ff-103-167-176-239.ngrok-free.app/job/Test/build" --user "admin:$JENKINS_TOKEN" -H "Jenkins-Crumb:$CRUMB"
        
        # curl -X POST "$JENKINS_URL" --user "$JENKINS_USER:$JENKINS_TOKEN" -H "Jenkins-Crumb:$CRUMB" 
